---
- name: Converge
  hosts: all
  tasks:
    - name: Include machine.workstation
      include_role:
        name: machine.workstation
    - name: Include machine.development
      include_role:
        name: machine.development
