---
- name: Side effects
  hosts: all
  vars:
    developer_machine: True
  tasks:
    - name: Include machine.workstation
      include_role:
        name: machine.workstation
    - name: Include machine.development
      include_role:
        name: machine.development
