---
- include_tasks: repos.yml

- include_tasks: packages.yml

- include_tasks: services.yml

- include_tasks: google_chrome.yml
  when: add_google_chrome|bool == True

- include_tasks: slack.yml
  when: workstation_slack|bool == True

# - include_tasks: networking.yml

- name: Stop tracker-store.desktop
  become: yes
  file:
    path: /etc/xdg/autostart/tracker-store.desktop
    state: absent
