---
- name: Install packages
  dnf:
    name: "{{ install_packages }}"
    state: latest
  become: true

- name: Remove some packages
  dnf:
    name: "{{ remove_packages }}"
    state: absent
  become: true
  when: remove_packages is defined

- name: Remove Evolution
  dnf:
    name: evolution
    state: absent
  become: true
  when: remove_evolution|bool == True
