---
name: Verification
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  molecule:
    name: Molecule Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro:
          - fedora41
#          - fedora42
#          - fedora43
#          - rocky8
#          - rocky9
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          pip install pre-commit
      - name: Test with molecule
        run: molecule test --scenario-name ${{ matrix.molecule_distro }}
