---
- name: Install packages
  dnf:
    name: "{{ install_packages }}"
    state: latest
  become: true

- name: Install groups of packages
  dnf:
    name:
      - "@c-development"
      - "@development-tools"
    state: present
  become: true
  when: ansible_version.full is version_compare('2.3.2.0', '>=')

- name: Install NodeJS
  dnf:
    name: nodejs
    state: present
  become: true
  when: nodejs_install|bool == True
